inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
   Max: 120

Style/Documentation:
  Enabled: false