stacks:
  url: 'https://stacks.stanford.edu'
  url_b: 'https://sul-stacks-prod-b.stanford.edu'

asset_host: '//127.0.0.1:3000'

purl:
  url: 'https://purl.stanford.edu'

purl_resource:
  public_xml: 'https://purl.stanford.edu/%{druid}.xml'

resource_cache:
  enabled: false